let mitzvahList = ["Tefillin",
"Mezuza", 
"Pushka",
 "Menorah", 
 "Moshiach", 
 "Latkes",
 "Lulav",
  "Esrog",
   "Shabbos Candles",
   "Shofar",
   "Challah Cover",
   "Chanuka Gelt",
   "Siddur",
   "Chumash",
   "Chitas",
   "Matzah",
   "Maror",
   "Charoses",
   "Afikomen",
   "Humantashen",
   "Kiddush Cup",
   "Gragger",
   "Kos Shel Eliyahu"
 ]

 console.log(mitzvahList)